
import javax.swing.JLabel;
import komponenty.Jlabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class ObliczeniaTest extends javax.swing.JPanel {

    /**
     * Creates new form ObliczeniaTest
     */
    public ObliczeniaTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sześcian = new komponenty.Przycisk();
        Prostopadłościan = new komponenty.Przycisk();
        Walec = new komponenty.Przycisk();
        Stożek = new komponenty.Przycisk();
        Koło = new komponenty.Przycisk();
        obliczeniaObj1 = new komponenty.ObliczeniaObj();
        X = new komponenty.Jlabel();
        Y = new komponenty.Jlabel();
        H = new komponenty.Jlabel();
        R = new komponenty.Jlabel();
        Figura = new komponenty.Jlabel();

        Sześcian.setLabel("Sześcian");
        Sześcian.setName("Sześcian"); // NOI18N
        Sześcian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SześcianActionPerformed(evt);
            }
        });

        Prostopadłościan.setLabel("Prostopadłościan");
        Prostopadłościan.setName("Prostopadłościan"); // NOI18N
        Prostopadłościan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProstopadłościanActionPerformed(evt);
            }
        });

        Walec.setLabel("Walec");
        Walec.setName("Walec"); // NOI18N
        Walec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WalecActionPerformed(evt);
            }
        });

        Stożek.setLabel("Stożek");
        Stożek.setName("Stożek"); // NOI18N
        Stożek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StożekActionPerformed(evt);
            }
        });

        Koło.setActionCommand("Koło");
        Koło.setLabel("Koło");
        Koło.setName("Koło"); // NOI18N
        Koło.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KołoActionPerformed(evt);
            }
        });

        X.setText("X: ");
        X.setToolTipText("");
        X.setName("X"); // NOI18N

        Y.setText("Y: ");

        H.setText("H: ");

        R.setText("R: ");

        Figura.setText("Figura");
        Figura.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                FiguraAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Figura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obliczeniaObj1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sześcian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Prostopadłościan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Walec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Stożek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Koło, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Koło, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stożek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Walec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prostopadłościan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sześcian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(Figura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obliczeniaObj1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SześcianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SześcianActionPerformed
        obliczeniaObj1.setWybor(1);
        String wzor = obliczeniaObj1.getWzor();
        Figura.setText(wzor);
// TODO add your handling code here:
    }//GEN-LAST:event_SześcianActionPerformed

    private void ProstopadłościanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProstopadłościanActionPerformed
         obliczeniaObj1.setWybor(2);
        String wzor = obliczeniaObj1.getWzor();
        Figura.setText(wzor);// TODO add your handling code here:
    }//GEN-LAST:event_ProstopadłościanActionPerformed

    private void WalecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WalecActionPerformed
        obliczeniaObj1.setWybor(3);
        String wzor = obliczeniaObj1.getWzor();
        Figura.setText(wzor); // TODO add your handling code here:
    }//GEN-LAST:event_WalecActionPerformed

    private void StożekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StożekActionPerformed
         obliczeniaObj1.setWybor(4);
        String wzor = obliczeniaObj1.getWzor();
        Figura.setText(wzor);// TODO add your handling code here:
    }//GEN-LAST:event_StożekActionPerformed

    private void KołoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KołoActionPerformed
         obliczeniaObj1.setWybor(5);
        String wzor = obliczeniaObj1.getWzor();
        Figura.setText(wzor);// TODO add your handling code here:
    }//GEN-LAST:event_KołoActionPerformed

    private void FiguraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_FiguraAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_FiguraAncestorAdded


   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObliczeniaTest().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private komponenty.Jlabel Figura;
    private komponenty.Jlabel H;
    private komponenty.Przycisk Koło;
    private komponenty.Przycisk Prostopadłościan;
    private komponenty.Jlabel R;
    private komponenty.Przycisk Stożek;
    private komponenty.Przycisk Sześcian;
    private komponenty.Przycisk Walec;
    private komponenty.Jlabel X;
    private komponenty.Jlabel Y;
    private komponenty.ObliczeniaObj obliczeniaObj1;
    // End of variables declaration//GEN-END:variables
}
